export type PlatformSearchItem = {
  id: string;
  title: string;
  description: string;
  href: string;
  category: "Página" | "Ação" | "Módulo";
  keywords: string[];
};

export const platformSearchItems: PlatformSearchItem[] = [
  {
    id: "home",
    title: "Início da loja",
    description: "Painel principal com vendas, clientes e estoque.",
    href: "/",
    category: "Página",
    keywords: ["home", "inicio", "painel", "dashboard", "loja"],
  },
  {
    id: "nova-venda",
    title: "Nova venda",
    description: "Registrar uma venda no balcão ou online.",
    href: "/vendas/nova",
    category: "Ação",
    keywords: ["venda", "pedido", "caixa", "online", "loja fisica"],
  },
  {
    id: "resumo-vendas",
    title: "Resumo de vendas",
    description: "Acompanhar resultado comercial e vendas recentes.",
    href: "/vendas",
    category: "Página",
    keywords: ["vendas", "resumo", "comercial", "faturamento"],
  },
  {
    id: "historico-vendas",
    title: "Histórico de vendas",
    description: "Consultar pedidos e vendas já registradas.",
    href: "/vendas/historico",
    category: "Página",
    keywords: ["historico", "pedido", "vendas", "consulta"],
  },
  {
    id: "relatorio-vendas",
    title: "Relatórios de vendas",
    description: "Ler comparativos e desempenho comercial.",
    href: "/vendas/relatorios",
    category: "Página",
    keywords: ["relatorio", "vendas", "comparativo", "ticket medio"],
  },
  {
    id: "clientes",
    title: "Clientes",
    description: "Ver cadastro e relacionamento com a loja.",
    href: "/cadastros/clientes",
    category: "Módulo",
    keywords: ["cliente", "cadastro", "relacionamento", "historico do cliente"],
  },
  {
    id: "novo-cliente",
    title: "Cadastro de cliente",
    description: "Abrir a área de clientes para cadastrar ou consultar.",
    href: "/cadastros/clientes",
    category: "Ação",
    keywords: ["novo cliente", "cadastrar cliente", "cadastro", "cliente"],
  },
  {
    id: "estoque",
    title: "Estoque",
    description: "Resumo do estoque com alertas e movimentações.",
    href: "/estoque",
    category: "Módulo",
    keywords: ["estoque", "resumo", "produtos", "movimentacoes"],
  },
  {
    id: "produtos-estoque",
    title: "Produtos",
    description: "Consultar produtos, saldo disponível e status.",
    href: "/estoque/produtos",
    category: "Página",
    keywords: ["produto", "sku", "estoque", "cadastro de produto"],
  },
  {
    id: "novo-produto",
    title: "Novo produto",
    description: "Cadastrar um item novo no estoque.",
    href: "/estoque/produtos/novo",
    category: "Ação",
    keywords: ["novo produto", "cadastro produto", "produto"],
  },
  {
    id: "movimentacoes-estoque",
    title: "Movimentações",
    description: "Entradas, saídas e ajustes do estoque.",
    href: "/estoque/movimentacoes",
    category: "Página",
    keywords: ["movimentacao", "entrada", "saida", "ajuste", "estoque"],
  },
  {
    id: "entradas-estoque",
    title: "Registrar entrada de estoque",
    description: "Dar entrada em mercadorias e atualizar o saldo.",
    href: "/estoque/entradas",
    category: "Ação",
    keywords: ["entrada", "recebimento", "estoque", "fornecedor"],
  },
  {
    id: "fornecedores",
    title: "Fornecedores",
    description: "Consultar parceiros e vínculo com produtos.",
    href: "/estoque/fornecedores",
    category: "Página",
    keywords: ["fornecedor", "estoque", "compras"],
  },
  {
    id: "relatorios-estoque",
    title: "Relatórios de estoque",
    description: "Ver ruptura, giro e itens abaixo do mínimo.",
    href: "/estoque/relatorios",
    category: "Página",
    keywords: ["relatorios", "estoque", "ruptura", "giro", "baixo estoque"],
  },
  {
    id: "financeiro",
    title: "Financeiro",
    description: "Resumo do caixa e movimentação financeira da loja.",
    href: "/financeiro",
    category: "Módulo",
    keywords: ["financeiro", "caixa", "fluxo", "contas"],
  },
  {
    id: "contas-pagar",
    title: "Contas a pagar",
    description: "Acompanhar saídas e compromissos da loja.",
    href: "/financeiro/contas-pagar",
    category: "Página",
    keywords: ["pagar", "despesas", "financeiro", "contas"],
  },
  {
    id: "contas-receber",
    title: "Contas a receber",
    description: "Ver entradas previstas e recebimentos.",
    href: "/financeiro/contas-receber",
    category: "Página",
    keywords: ["receber", "financeiro", "pagamentos", "recebimentos"],
  },
  {
    id: "fluxo-caixa",
    title: "Fluxo de caixa",
    description: "Acompanhar entradas e saídas do período.",
    href: "/financeiro/fluxo-caixa",
    category: "Página",
    keywords: ["caixa", "fluxo", "financeiro"],
  },
  {
    id: "tarefas",
    title: "Tarefas",
    description: "Organizar pendências e rotina da operação.",
    href: "/tarefas",
    category: "Módulo",
    keywords: ["tarefas", "pendencias", "rotina"],
  },
  {
    id: "ajuda",
    title: "Ajuda",
    description: "Acessar orientações e suporte da plataforma.",
    href: "/configuracoes/ajuda",
    category: "Página",
    keywords: ["ajuda", "suporte", "faq"],
  },
  {
    id: "configuracoes",
    title: "Configurações",
    description: "Ajustar conta e preferências do sistema.",
    href: "/configuracoes",
    category: "Página",
    keywords: ["config", "configuracoes", "preferencias", "ajustes"],
  },
];
